class InvitationFailure(Exception):
    pass


class InviteAlreadyAccepted(Exception):
    pass
